import {
    Loader2,
    LayoutDashboard,
    Users,
    Calendar,
    CreditCard,
    Settings,
    LogOut,
    Plus,
    Search,
    Bell,
    Menu,
    X,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    MoreVertical,
    Check,
    AlertCircle,
    FileText,
    User,
    Mail,
    Phone,
    MapPin,
    Activity,
    Pill,
    Stethoscope,
    Clock,
    DollarSign,
    TrendingUp,
    ArrowUpRight,
    ArrowDownRight,
    ArrowUp,
    ArrowDown,
    Filter,
    Download,
    Trash2,
    Edit,
    Eye,
    MoreHorizontal,
    Sun
} from "lucide-react";

export const Icons = {
    spinner: Loader2,
    dashboard: LayoutDashboard,
    patients: Users,
    appointments: Calendar,
    billing: CreditCard,
    settings: Settings,
    logout: LogOut,
    add: Plus,
    search: Search,
    bell: Bell,
    menu: Menu,
    close: X,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    moreVertical: MoreVertical,
    moreHorizontal: MoreHorizontal,
    check: Check,
    alert: AlertCircle,
    file: FileText,
    user: User,
    mail: Mail,
    phone: Phone,
    mapPin: MapPin,
    activity: Activity,
    pill: Pill,
    stethoscope: Stethoscope,
    clock: Clock,
    dollar: DollarSign,
    trendingUp: TrendingUp,
    arrowUpRight: ArrowUpRight,
    arrowDownRight: ArrowDownRight,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    filter: Filter,
    download: Download,
    trash: Trash2,
    edit: Edit,
    eye: Eye,
    sun: Sun,
};
